"groups":
- "name": "opencost"
  "rules":
  - "alert": "OpenCostMonthlyBudgetExceeded"
    "annotations":
      "dashboard_url": "https://grafana.com/d/opencost-mixin-kover-jkwq/opencost-overview"
      "description": "The monthly budget for the cluster has been exceeded. Consider scaling down resources or increasing the budget."
      "summary": "OpenCost Monthly Budget Exceeded"
    "expr": |
      (
        sum(
          node_total_hourly_cost{
            job=~"opencost"
          }
        ) * 730
        or vector(0)
      )
      +
      (
        sum(
          sum(
            kube_persistentvolume_capacity_bytes{
              job=~"opencost"
            }
            / 1024 / 1024 / 1024
          ) by (persistentvolume)
          *
          sum(
            pv_hourly_cost{
              job=~"opencost"
            }
          ) by (persistentvolume)
        ) * 730
        or vector(0)
      )
      > 200
    "for": "30m"
    "labels":
      "severity": "warning"
  - "alert": "OpenCostAnomalyDetected"
    "annotations":
      "dashboard_url": "https://grafana.com/d/opencost-mixin-kover-jkwq/opencost-overview"
      "description": "A significant increase in cluster costs has been detected. The average hourly cost over the 3 hours exceeds the 7-day average by more than 20%. This could indicate unexpected resource usage or cost-related changes in the cluster."
      "summary": "OpenCost Cost Anomaly Detected"
    "expr": |
      1 -
      (
        avg_over_time(
          sum(
            node_total_hourly_cost{
              job=~"opencost"
            }
          ) [7d:1h]
        )
        /
        avg_over_time(
          sum(
            node_total_hourly_cost{
              job=~"opencost"
            }
          ) [3h:30m]
        )
      ) > 0.20000000000000001
    "for": "10m"
    "labels":
      "severity": "warning"
