"groups":
- "name": "opencost"
  "rules":
  - "alert": "OpenCostMonthlyBudgetExceeded"
    "annotations":
      "dashboard_url": "https://grafana.com/d/opencost-mixin-kover-jkwq/opencost-overview"
      "description": "The monthly budget for the cluster has been exceeded. Consider scaling down resources or increasing the budget."
      "summary": "OpenCost Monthly Budget Exceeded"
    "expr": |
      (
        sum(
          node_total_hourly_cost{
            job=~"opencost"
          }
        ) * 730
        or vector(0)
      )
      +
      (
        sum(
          sum(
            kube_persistentvolume_capacity_bytes{
              job=~"opencost"
            }
            / 1024 / 1024 / 1024
          ) by (persistentvolume)
          *
          sum(
            pv_hourly_cost{
              job=~"opencost"
            }
          ) by (persistentvolume)
        ) * 730
        or vector(0)
      )
      > 200
    "for": "30m"
    "labels":
      "severity": "warning"
