{
 "title": "OpenCost / Overview",
 "description": "A dashboard that monitors OpenCost and focuses on giving a overview for OpenCost. It is created using the [opencost-mixin](https://github.com/adinhodovic/opencost-mixin).",
 "tags": [
  "opencost",
  "opencost-mixin"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(opencost_build_info, job)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hourly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) \n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) \n"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) * 24\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) * 24\n"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) * 730\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (10730 * 10730 * 10730)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) * 730\n"
    }
   ]
  },
  {
   "title": "Monthly CPU Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 730\n)\n"
    }
   ]
  },
  {
   "title": "Monthly Ram Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 730\n)\n"
    }
   ]
  },
  {
   "title": "Monthly PV Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (persistentvolume)\n) * 730\n"
    }
   ]
  },
  {
   "title": "Hourly Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) \n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) \n",
     "legendFormat": "Hourly Cost"
    }
   ]
  },
  {
   "title": "Daily Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) * 24\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) * 24\n",
     "legendFormat": "Daily Cost"
    }
   ]
  },
  {
   "title": "Monthly Cost",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) * 730\n+\nsum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (10730 * 10730 * 10730)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n  sum(\n    pv_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (persistentvolume)\n) * 730\n",
     "legendFormat": "Monthly Cost"
    }
   ]
  },
  {
   "title": "Cost by Resource",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 730\n)\n",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 730\n)\n",
     "legendFormat": "RAM"
    },
    {
     "expr": "sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (persistentvolume)\n) * 730\n",
     "legendFormat": "PV"
    }
   ]
  },
  {
   "title": "Cost by Namespace",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_ram_hourly_cost{job=~\"$job\"} / (1024 * 1024 * 1024) * 730)\n    +\n    sum(\n      container_cpu_allocation{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_cpu_hourly_cost{job=~\"$job\"} * 730)\n  ) by (namespace)\n)\n",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Cost by Instance Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    node_total_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (instance_type) * 730\n)\n",
     "legendFormat": "{{ instance_type }}"
    }
   ]
  },
  {
   "title": "Total Cost Variance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 -\n(\n  avg_over_time(\n    sum(node_total_hourly_cost{job=~\"$job\"}) [7d:1h]\n  )\n  /\n  avg_over_time(\n    sum(node_total_hourly_cost{job=~\"$job\"}) [1d:1h]\n  )\n)\n",
     "legendFormat": "Current hourly cost vs. 7-day average"
    },
    {
     "expr": "1 -\n(\n  avg_over_time(\n    sum(node_total_hourly_cost{job=~\"$job\"}) [30d:1h]\n  )\n  /\n  avg_over_time(\n    sum(node_total_hourly_cost{job=~\"$job\"}) [1d:1h]\n  )\n)\n",
     "legendFormat": "Current hourly cost vs. 30-day average"
    }
   ]
  },
  {
   "title": "Resource Cost Variance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 -\n(\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 730\n)\n [30d:1h]\n  )\n  /\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"cpu\",\n      unit=\"core\"\n    }\n  ) by (node)\n  * on(node) group_left()\n    sum(\n      node_cpu_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 730\n)\n [1d:1h]\n  )\n)\n",
     "legendFormat": "Current CPU hourly cost vs. 30-day average"
    },
    {
     "expr": "1 -\n(\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 730\n)\n [30d:1h]\n  )\n  /\n  avg_over_time(\n    sum(\n  sum(\n    kube_node_status_capacity{\n      job=~\"$job\",\n      resource=\"memory\",\n      unit=\"byte\"\n    }\n  ) by (node)\n  / (1024 * 1024 * 1024)\n  * on(node) group_left()\n    sum(\n      node_ram_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (node)\n  * 730\n)\n [1d:1h]\n  )\n)\n",
     "legendFormat": "Current RAM hourly cost vs. 30-day average"
    },
    {
     "expr": "1 -\n(\n  avg_over_time(\n    (sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (persistentvolume)\n) * 730\n) [30d:1h]\n  )\n  /\n  avg_over_time(\n    (sum(\n  sum(\n    kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    } / (1024 * 1024 * 1024)\n  ) by (persistentvolume)\n  * on(persistentvolume) group_left()\n    sum(\n      pv_hourly_cost{\n        job=~\"$job\"\n      }\n    ) by (persistentvolume)\n) * 730\n) [1d:1h]\n  )\n)\n",
     "legendFormat": "Current PV hourly cost vs. 30-day average"
    }
   ]
  },
  { "title": "Cloud Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Nodes Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    job=~\"$job\",\n    resource=\"cpu\",\n    unit=\"core\"\n  }\n) by (node)\n* on(node) group_left(instance_type, arch)\n  sum(\n    node_cpu_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (node, instance_type, arch)\n* 730\n"
    },
    {
     "expr": "sum(\n  kube_node_status_capacity{\n    job=~\"$job\",\n    resource=\"memory\",\n    unit=\"byte\"\n  }\n) by (node)\n/ (1024 * 1024 * 1024)\n* on(node) group_left(instance_type, arch)\n  sum(\n    node_ram_hourly_cost{\n      job=~\"$job\"\n    }\n  ) by (node, instance_type, arch)\n* 730\n"
    },
    {
     "expr": "sum(\n  node_total_hourly_cost{\n    job=~\"$job\"\n  }\n) by (node, instance_type, arch)\n* 730\n"
    }
   ]
  },
  {
   "title": "Persistent Volumes Monthly Cost",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum(\n  kube_persistentvolume_capacity_bytes{\n    job=~\"$job\"\n  }\n  / 1024 / 1024 / 1024\n) by (persistentvolume)\n"
    },
    {
     "expr": "sum(\n  kube_persistentvolume_capacity_bytes{\n      job=~\"$job\"\n    }\n  / 1024 / 1024 / 1024\n) by (persistentvolume)\n*\nsum(\n  pv_hourly_cost{\n    job=~\"$job\"\n  }\n  * 730\n) by (persistentvolume)\n"
    }
   ]
  },
  { "title": "Namespace Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Namespace Monthly Cost",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "topk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_ram_hourly_cost{job=~\"$job\"} / (1024 * 1024 * 1024) * 730)\n    +\n    sum(\n      container_cpu_allocation{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_cpu_hourly_cost{job=~\"$job\"} * 730)\n  ) by (namespace)\n)\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_ram_hourly_cost{job=~\"$job\"} / (1024 * 1024 * 1024) * 730)\n    +\n    sum(\n      container_cpu_allocation{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_cpu_hourly_cost{job=~\"$job\"} * 730)\n  ) by (namespace)\n)\n\n/\ntopk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{job=~\"$job\"} offset 7d\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_ram_hourly_cost{job=~\"$job\"} offset 7d / (1024 * 1024 * 1024) * 730)\n    +\n    sum(\n      container_cpu_allocation{job=~\"$job\"} offset 7d\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_cpu_hourly_cost{job=~\"$job\"} offset 7d * 730)\n  ) by (namespace)\n)\n\n* 100\n- 100\n"
    },
    {
     "expr": "topk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_ram_hourly_cost{job=~\"$job\"} / (1024 * 1024 * 1024) * 730)\n    +\n    sum(\n      container_cpu_allocation{job=~\"$job\"}\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_cpu_hourly_cost{job=~\"$job\"} * 730)\n  ) by (namespace)\n)\n\n/\ntopk(10,\n  sum(\n    sum(\n      container_memory_allocation_bytes{job=~\"$job\"} offset 30d\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_ram_hourly_cost{job=~\"$job\"} offset 30d / (1024 * 1024 * 1024) * 730)\n    +\n    sum(\n      container_cpu_allocation{job=~\"$job\"} offset 30d\n    ) by (namespace, instance)\n    * on(instance) group_left()\n      (node_cpu_hourly_cost{job=~\"$job\"} offset 30d * 730)\n  ) by (namespace)\n)\n\n* 100\n- 100\n"
    }
   ]
  }
 ]
}